export const users = [
  {
    id: 1,
    name: "Joaquin",
    lastname: "Abadia",
    age: 30,
    phone: "123456789",
    email: "joaquin@gmail.com",
  },
  {
    id: 2,
    name: "Mariano",
    lastname: "Collovatti",
    age: 25,
    phone: "987654321",
    email: "mariano@gmail.com",
  },
  {
    id: 3,
    name: "Michael",
    lastname: "Smith",
    age: 35,
    phone: "123987456",
    email: "michael.smith@gmail.com",
  },
  {
    id: 4,
    name: "Sarah",
    lastname: "Connor",
    age: 40,
    phone: "456123789",
    email: "sara.conor@gmail.com",
  },
  {
    id: 5,
    name: "Emiliano",
    lastname: "Connor",
    age: 25,
    phone: "001001001",
    email: "emi@gmail.com",
  },
];
