let alumnos = [
  {
    nombre: "Jhoceliz",
    apellido: "Gonzalez",
    curso: "Backend",
    edad: 20,
    correo: "jhoceliz@gmail.com",
    genero: "Femenino",
  },
  {
    nombre: "Jhon",
    apellido: "Lopez",
    curso: "Frontend",
    edad: 5,
    correo: "jhon@gmail.com",
    genero: "Masculino",
  },
  {
    nombre: "Sandra",
    apellido: "Garcia",
    curso: "Backend",
    edad: 30,
    correo: "sandra@gmail.com",
    genero: "Femenino",
  },
  {
    nombre: "Ivan",
    apellido: "Ramirez",
    curso: "Frontend",
    edad: 25,
    correo: "ivan@gmail.com",
    genero: "Masculino",
  },
  {
    nombre: "Luis",
    apellido: "Menendez",
    curso: "Backend",
  },
];
let alumnosTwo = [
  {
    nombre: "Walter",
    apellido: "Maza",
    curso: "Python",
    edad: 28,
    correo: "walter@gmail.com",
    genero: "Masculino",
  },
  {
    nombre: "Alber",
    apellido: "Lopez",
    curso: "Cocina",
    edad: 35,
    correo: "alberto@gmail.com",
  },
  {
    nombre: "Sarai",
    apellido: "Perez",
    curso: "Backend",
    edad: 33,
    correo: "sara@gmail.com",
    genero: "Femenino",
  },
  {
    nombre: "Maria",
    apellido: "Soriano",
    correo: "maria@gmail.com",
  },
  {
    nombre: "Tomas",
    apellido: "Alvarez",
    curso: "Backend",
    edad: 25,
  },
];
